language: python
os: linux
python: "3.7"
dist: xenial
compiler:
    - gcc
script:
    - cmake .
    - make
    - cp ext/libbar/libbar/*libbar.* src/
    - cp ext/libfoo/libfoo/*libfoo.* src/
    - src/fancyexe # testing

