language: python
os: linux
python: "3.7"
dist: xenial
compiler:
    - gcc
script:
    - cmake .
    - make
    - cp bin/ext/libbar/libbar/*libbar.* bin/src/
    - cp bin/ext/libfoo/libfoo/*libfoo.* bin/src/
    - bin/src/fancyexe # testing

